# Changes here will be overwritten by Copier
_commit: v0.1.0a6
_src_path: gh:edgarrmondragon/singer-tap-copier-template
author_email: edgarrmondragon@hey.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: Etc/UTC
python_main_version: '3.12'
repository_name: tap-readme
repository_namespace: edgarrmondragon
repository_provider: github.com
repository_visibility: private
tap_auth_method: Basic Auth
tap_id: tap-readme
tap_package_command_line_name: tap-readme
tap_package_distribution_name: tap-readme
tap_package_import_name: tap_readme
tap_source_description: ReadMe transforms your API docs into interactive hubs that
    help developers succeed.
tap_source_id: ReadMe
tap_source_name: ReadMe.com
tap_stream_type: REST
vscode_files: true
